version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
before_build:
- cmd: nuget restore
configuration: Release
artifacts:
  - path: Cobalt.Setup\bin\Release\Cobalt.Setup.msi
    name: Cobalt.Setup
build:
  verbosity: minimal