version: 0.5.{build}
branches:
  only:
  - master
image: Visual Studio 2017
before_build:
- cmd: nuget restore
configuration: Release
artifacts:
  - path: Cobalt.Setup\bin\$(configuration)\Cobalt.Setup.msi
    name: Cobalt.Setup
build:
  verbosity: minimal
deploy:
  release: Cobalt-v$(APPVEYOR_REPO_TAG_NAME)
  description: 'Release Description'
  provider: GitHub
  auth_token:
    secure: KPqbxET+Zf8VS04w1f49Aick7IiASzolYqDNHij5pln0e690/t7IuvSq1W0OhTHf
  artifact: Cobalt.Setup\bin\$(configuration)\Cobalt.Setup.msi
  draft: true
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true