[project]
name = "cobalt"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["integration-py"]



[dependency-groups]
dev = [
    "ruff>=0.12.3",
]

[tool.uv.sources]
integration-py = { workspace = true }

[tool.uv.workspace]
members = ["tests/integration-py"]
