//! Desktop Platform interactions

/// Website/Browser Platform
pub mod browser;
mod buf;
mod error;
/// Events generated by the Platform
pub mod events;
/// Objects in the Platform
pub mod objects;

use util::error::{Context, Result};
use windows::Win32::System::Com::{COINIT_MULTITHREADED, CoInitializeEx};

use crate::objects::Timestamp;

/// Setup platform for Windows
pub fn setup() -> Result<()> {
    Timestamp::setup()?;
    unsafe { CoInitializeEx(None, COINIT_MULTITHREADED) }
        .ok()
        .context("com init")?;
    Ok(())
}
