name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  
  js:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: src/ui

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '23.5.0'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.2

      - name: Install Dependencies
        run: bun install --frozen-lockfile
        
      # don't bother building the js side - tauri will do that

      - name: Type Check
        run: bun typecheck

      - name: Format Check
        run: bun format

      - name: Lint Check
        run: bun lint


  rust:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Update Rust Toolchain
        uses: dtolnay/rust-toolchain@1.85.0
        with:
          components: rustfmt, clippy
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --verbose # this might download deps, should be cached
      - name: Test
        run: cargo test --verbose # this also downloads deps, but not cached...
      - name: Lint (Format)
        run: cargo fmt --all -- --check
      - name: Lint (Clippy)
        run: cargo clippy --frozen --locked -- -D warnings

  tauri:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Update Rust Toolchain
        uses: dtolnay/rust-toolchain@1.85.0
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '23.5.0'
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.2
      - name: Install Dependencies
        working-directory: src/ui
        run: bun install --frozen-lockfile

      - name: Build Tauri App only
        if: github.ref != 'refs/heads/main'
        uses: tauri-apps/tauri-action@v0
        with:
          projectPath: src/ui
          tauriScript: bun tauri
      - name: Build Tauri App (nightly)
        if: github.ref == 'refs/heads/main'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: src/ui
          includeUpdaterJson: true
          tauriScript: bun tauri
          tagName: nightly