name: release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  
  release:
    runs-on: windows-latest
    environment: Production Release
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Update Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      - name: Set up cargo cache
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '23.5.0'
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.2
      - name: Install Dependencies
        working-directory: src/ui
        run: bun install --frozen-lockfile

      - name: Build Tauri App (Release Tag)
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
        with:
          projectPath: src/ui
          args: -c ./src-tauri/tauri.conf.release.json
          includeUpdaterJson: true
          tauriScript: bun tauri
          tagName: v__VERSION__
          releaseName: "Cobalt v__VERSION__"
          releaseDraft: true
          prerelease: false