name: release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10

jobs:
  
  release:
    runs-on: windows-latest
    environment: Production Release
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Update Rust Toolchain
        uses: dtolnay/rust-toolchain@1.85.0
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '23.5.0'
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.2
      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build Tauri App (Release Tag)
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
        with:
          args: -c ./src/ui/src-tauri/tauri.conf.release.json
          includeUpdaterJson: true
          tauriScript: bun tauri
          tagName: v__VERSION__
          releaseName: "Cobalt v__VERSION__"
          releaseDraft: true
          prerelease: false
